[package]
name = "particles"
version = "0.1.0"
authors = ["manthanmabc <manthanmji@gamil.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.30.0"
rand = "*"